apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    env: dev
    app: django
spec:
  startingDeadlineSeconds: 60
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: django_app:latest
            imagePullPolicy: Never
            command: [./manage.py, clearsessions]
            envFrom:
            - configMapRef:
                name: django-config
          restartPolicy: OnFailure
